export const ASSIGNMENT_ISSUE_CODES = {
  DRIVER_NOT_ASSIGNED: 'DRIVER_NOT_ASSIGNED',
  VEHICLE_NOT_ASSIGNED: 'VEHICLE_NOT_ASSIGNED',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_INACTIVE: 'DRIVER_INACTIVE',
  DRIVER_ON_LEAVE: 'DRIVER_ON_LEAVE',
  DRIVER_LICENSE_MISSING: 'DRIVER_LICENSE_MISSING',
  DRIVER_DOUBLE_BOOKED: 'DRIVER_DOUBLE_BOOKED',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  VEHICLE_UNAVAILABLE: 'VEHICLE_UNAVAILABLE',
  VEHICLE_DOUBLE_BOOKED: 'VEHICLE_DOUBLE_BOOKED',
} as const
